theme: jekyll-theme-leap-day
plugins:
  - jekyll-relative-links
relative_links:
  enabled:     true
  collections: true
include:
  - README.md
  - docs/INSTALL.md
  - docs/LICENSE.md
  - docs/TODO.md
  - docs/USAGE.md
